### PR TITLE
fix(RoleObjectFactory): Resolve typo for removeChildAt call

### PR DESCRIPTION
**Pull request by Dossar**
### Summary of Changes
Currently there seems to be a typo in CAM 1.0.0 that was introduced in #24:
https://github.com/CurriculumAssociates/createjs-accessibility/blob/6f8dc12d2f3111aa6389e2a47199419606867f5a/src/RoleObjectFactory.js#L96

It looks like it was trying to reference this method, but had an extra d.
https://github.com/CurriculumAssociates/createjs-accessibility/blob/6f8dc12d2f3111aa6389e2a47199419606867f5a/src/RoleObjects/AccessibilityObject.js#L119

This typo results in the following error:
```
`TypeError: obj.removedChildAt is not a function`
```

### CODE REVIEW

**Review by mnewcomb314 — APPROVED** [review]

**Review by mnewcomb314 — APPROVED** [review]

**Comment by Dossar** [comment]
Since this PR is stuck, go to https://github.com/CurriculumAssociates/createjs-accessibility/pull/45 instead.
